### ISSUE TITLE
In leiu of a PR..

### ISSUE THREAD

**Issue by kfiresmith** [idiv-biodiversity/ansible-role-systemd-resolved#2]
Hallo Christian,
I apologize for the format, but I don't think I have the cycles to do a formal PR for these fixes right now.

I've forked your role and in a single multi-change commit (yuck, I know :) ), I've fixed or made more widely useful a few things with this role, and have described them in the commit.

https://github.com/kfiresmith/ansible-role-systemd-resolved/commit/d1c1323ce841696fb94af4a56acb06be569a8a60

I'm not completely convinced that we should be doing service management in tasks/main w/o invoking a handler as well, but I wanted to functionally change as little of your code as possible to make the changes more palatable.  

Aside from making the role useful outside of Arch, the biggest changes were to ensure that service management happens last so that you don't end up with a temporary resolution problem between when the service is restarted and the resolv.conf file is managed, as well as changing the logic of the resolv.conf symlink to intelligently choose which run file to link to based on whether a person chooses to use a stub resolver or not.

Please let me know what you think about these changes, and do feel free to pull them in sans-PR (which would let me drop my local fork and go happily back to your Galaxy role :)

Thanks!

**Comment by wookietreiber** [comment]
I recently updated the role and some of your changes are in now. If you do find the time, feel free to provide proper PRs for the individual changes to be discussed.
